version: "3"
services:
  db:
    image: mysql:8.0
    restart: always
    command:
      - --lower_case_table_names=1
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=mydb
      - MYSQL_ROOT_PASSWORD=qwe123
      - TZ=Asia/Seoul
    volumes:
      - /Users/hee/Desktop/github_repo/java-springboot-tutorial/05. mysql/mysql